var bcSetInfo = {
	"title": "白鸽 电子目录",
	"desc": "",
	"pt": "aXNucQ==",
	"pass": "0",
	"openType": 1,
	"bMode": 3,
	"showPage": 1,
	"isShowThumb": 1,
	"skin": "silver",
	"isShowSearch": 1,
	"isShowContact": 1,
	"isShowShare": 1,
	"isShowSkin": 1,
	"isShowCategory": 0,
	"status": 1,
	"showInfo": 1,
	"isFolderList": 0,
	"isShowLogo": 1,
	"logoName": "baige_book_190_65.png",
	"logoLink": "",
	"showCover": 0,
	"showText": 0,
	"noShareWechat": 0,
	"onlyViewWechat": 0,
	"bookcaseLink": "isnq",
	// "imgUrl": "https:\/\/book.yunzhan365.com\/olze\/isnq_bookcase_logo.png?1594270803",
	// "caseLink": "https:\/\/book.yunzhan365.com\/bookcase\/isnq\/index.html"
}